<?php

/**
 * @file
 * Enables your site to capture votes on different topics in the form of multiple
 * choice questions.
 */

/**
 * Implements hook_help().
 */
function mimi_poll_help($path, $arg) {
  switch ($path) {
    case 'admin/help#mimi_poll':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Poll module can be used to create simple surveys or questionnaires that display cumulative results. A mimi_poll is a good way to receive feedback from site users and community members. For more information, see the online handbook entry for the <a href="@mimi_poll">Poll module</a>.', array('@mimi_poll' => 'http://drupal.org/documentation/modules/mimi_poll/')) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Creating a mimi_poll') . '</dt>';
      $output .= '<dd>' . t('Users can create a mimi_poll by clicking on Poll on the <a href="@add-content">Add new content</a> page, and entering the question being posed, the answer choices, and beginning vote counts for each choice. The status (closed or active) and duration (length of time the mimi_poll remains active for new votes) can also be specified.', array('@add-content' => url('node/add'))) . '</dd>';
      $output .= '<dt>' . t('Viewing mimi_polls') . '</dt>';
      $output .= '<dd>' . t('You can visit the <a href="@mimi_poll">Polls</a> page to view all current mimi_polls, or alternately enable the <em>Most recent mimi_poll</em> block on the <a href="@blocks">Blocks administration page</a>. To vote in or view the results of a specific mimi_poll, you can click on the mimi_poll itself.', array('@mimi_poll' => url('mimi_poll'), '@blocks' => url('admin/structure/block'))) . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function mimi_poll_theme() {
  $theme_hooks = array(
    'mimi_poll_vote' => array(
      'template' => 'mimi_poll_vote',
      'render element' => 'form',
    ),
    'mimi_poll_choices' => array(
      'render element' => 'form',
    ),
    'mimi_poll_results' => array(
      'template' => 'mimi_poll-results',
      'variables' => array('raw_title' => NULL, 'results' => NULL, 'votes' => NULL, 'raw_links' => NULL, 'block' => NULL, 'nid' => NULL, 'vote' => NULL),
    ),
    'mimi_poll_bar' => array(
      'template' => 'mimi_poll-bar',
      'variables' => array('title' => NULL, 'votes' => NULL, 'total_votes' => NULL, 'vote' => NULL, 'block' => NULL),
    ),
  );
  // The theme system automatically discovers the theme's functions and
  // templates that implement more targeted "suggestions" of generic theme
  // hooks. But suggestions implemented by a module must be explicitly
  // registered.
  $theme_hooks += array(
    'mimi_poll_results__block' => array(
      'template' => 'mimi_poll-results--block',
      'variables' => $theme_hooks['mimi_poll_results']['variables'],
    ),
    'mimi_poll_bar__block' => array(
      'template' => 'mimi_poll-bar--block',
      'variables' => $theme_hooks['mimi_poll_bar']['variables'],
    ),
  );
  return $theme_hooks;
}

/**
 * Implements hook_permission().
 */
function mimi_poll_permission() {
  $perms = array(
    'vote on mimi_polls' => array(
      'title' => t('Vote on mimi_polls'),
    ),
    'cancel own vote' => array(
      'title' => t('Cancel and change own votes'),
    ),
    'inspect all votes' => array(
      'title' => t('View details for all votes'),
    ),
  );

  return $perms;
}

/**
 * Implements hook_menu().
 */
function mimi_poll_menu() {
  $items['mimi_poll'] = array(
    'title' => 'Polls',
    'page callback' => 'mimi_poll_page',
//    'access arguments' => TRUE,
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'mimi_poll.pages.inc',
  );

  $items['node/%node/votes'] = array(
    'title' => 'Votes',
    'page callback' => 'mimi_poll_votes',
    'page arguments' => array(1),
    'access callback' => '_mimi_poll_menu_access',
    'access callback' => array('vote on mimi_polls'),
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
    'file' => 'mimi_poll.pages.inc',
  );

  $items['node/%node/results'] = array(
    'title' => 'Results',
    'page callback' => 'mimi_poll_results',
    'page arguments' => array(1),
    'access callback' => true,
    'weight' => 3,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'mimi_poll.pages.inc',
  );


  return $items;
}

/**
 * Callback function to see if a node is acceptable for mimi_poll menu items.
 */
function _mimi_poll_menu_access($node, $perm, $inspect_allowvotes) {
  return user_access($perm) && ($node->type == 'mimi_poll') && ($node->allowvotes || !$inspect_allowvotes);
}

/**
 * Implements hook_block_info().
 */
function mimi_poll_block_info() {
  $blocks['recent']['info'] = t('תוצאות סקר נוכחי');
  $blocks['recent']['properties']['administrative'] = TRUE;
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * Generates a block containing the latest mimi_poll.
 */
function mimi_poll_block_view($delta = '') {
  //if (user_access('access content')) {
    // Retrieve the latest mimi_poll.
    $select = db_select('node', 'n');
    $select->join('mimi_poll', 'p', 'p.nid = n.nid');
    $select->fields('n', array('nid'))
      ->condition('n.status', 1)
      ->orderBy('n.created', 'DESC')
      ->range(0, 1)
      ->addTag('node_access');

    $record = $select->execute()->fetchObject();
    if ($record) {
      $mimi_poll = node_load($record->nid);
      if ($mimi_poll->nid) {
        $mimi_poll = mimi_poll_block_latest_mimi_poll_view($mimi_poll);
        $block['subject'] = t('Poll');
        $block['content'] = $mimi_poll->content;
        return $block;
      }
    }
  //}
}

/**
 * Implements hook_cron().
 *
 * Closes mimi_polls that have exceeded their allowed runtime.
 */
function mimi_poll_cron() {
    //  $nids = db_query('SELECT p.nid FROM {mimi_poll} p INNER JOIN {node} n ON p.nid = n.nid WHERE (n.created + p.runtime) < :request_time AND p.active = :active AND p.runtime <> :runtime', array(':request_time' => REQUEST_TIME, ':active' => 1, ':runtime' => 0))->fetchCol();
    //  if (!empty($nids)) {
    //    db_update('mimi_poll')
    //      ->fields(array('active' => 0))
    //      ->condition('nid', $nids, 'IN')
    //      ->execute();
    //  }
}

/**
 * Implements hook_node_info().
 */
function mimi_poll_node_info() {
  return array(
    'mimi_poll' => array(
      'name' => t('Poll'),
      'base' => 'mimi_poll',
      'description' => t('A <em>mimi_poll</em> is a question with a set of possible responses. A <em>mimi_poll</em>, once created, automatically provides a simple running count of the number of votes received for each response.'),
      'title_label' => t('Question'),
      'has_body' => FALSE,
    )
  );
}

/**
 * Implements hook_field_extra_fields().
 */
function mimi_poll_field_extra_fields() {
  $extra['node']['mimi_poll'] = array(
    'form' => array(
      'choice_wrapper' => array(
        'label' => t('Poll choices'),
        'description' => t('Poll choices'),
        'weight' => -4,
      ),
      'settings' => array(
        'label' => t('Poll settings'),
        'description' => t('Poll module settings'),
        'weight' => -3,
      ),
    ),
    'display' => array(
      'mimi_poll_view_voting' => array(
        'label' => t('Poll vote'),
        'description' => t('Poll vote'),
        'weight' => 0,
      ),
      'mimi_poll_view_results' => array(
        'label' => t('Poll results'),
        'description' => t('Poll results'),
        'weight' => 0,
      ),
    )
  );

  return $extra;
}

/**
 * Implements hook_form().
 */
function mimi_poll_form($node, &$form_state) {
    // drupal_add_css( '.node-mimi_poll-form .vertical-tabs,.form-item-title{display: none};',array('group' => CSS_THEME,'type' => 'inline','media' => 'screen','preprocess' => FALSE,'weight' => '9999'));
    global $user;

  $admin = user_access('bypass node access') || user_access('edit any mimi_poll content') || (user_access('edit own mimi_poll content') && $user->uid == $node->uid);

  $type = node_type_get_type($node);

  // The submit handlers to add more mimi_poll choices require that this form is
  // cached, regardless of; whether Ajax is used.
  $form_state['cache'] = TRUE;

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => "NA",
    '#weight' => -5,
  );

  if (isset($form_state['choice_count'])) {
    $choice_count = $form_state['choice_count'];
  }
  else {
    $choice_count = max(2, empty($node->choice) ? 2 : count($node->choice));
  }

  // Add a wrapper for the choices and more button.
  $form['choice_wrapper'] = array(
    '#tree' => FALSE,
    '#weight' => -4,
    '#prefix' => '<div class="clearfix" id="mimi_poll-choice-wrapper">',
    '#suffix' => '</div>',
  );

  // Container for just the mimi_poll choices.
  $form['choice_wrapper']['choice'] = array(
    '#prefix' => '<div id="mimi_poll-choices">',
    '#suffix' => '</div>',
    '#theme' => 'mimi_poll_choices',
  );

  // Add the current choices to the form.
  $delta = 0;
  $weight = 0;
  if (isset($node->choice)) {
    $delta = count($node->choice);
    foreach ($node->choice as $chid => $choice) {
      $key = 'chid:' . $chid;
      $form['choice_wrapper']['choice'][$key] = _mimi_poll_choice_form($key, $choice['chid'], $choice['chtext'], $choice['chvotes'], $choice['weight'], $choice_count);
      $weight = max($choice['weight'], $weight);
    }
  }

  // Add initial or additional choices.
  $existing_delta = $delta;
  for ($delta; $delta < $choice_count; $delta++) {
    $key = 'new:' . ($delta - $existing_delta);
    // Increase the weight of each new choice.
    $weight++;
    $form['choice_wrapper']['choice'][$key] = _mimi_poll_choice_form($key, NULL, '', 0, $weight, $choice_count);
  }

  // We name our button 'mimi_poll_more' to avoid conflicts with other modules using
  // Ajax-enabled buttons with the id 'more'.
  $form['choice_wrapper']['mimi_poll_more'] = array(
    '#type' => 'submit',
    '#value' => t('More choices'),
    '#attributes' => array(
      'title' => t("If the amount of boxes above isn't enough, click here to add more choices."),
    ),
    '#weight' => 1,
    '#limit_validation_errors' => array(array('choice')),
    '#submit' => array('mimi_poll_more_choices_submit'),
    '#ajax' => array(
      'callback' => 'mimi_poll_choice_js',
      'wrapper' => 'mimi_poll-choices',
      'effect' => 'fade',
    ),
  );

  // Poll attributes
  $duration = array(
    // 1-6 minutes 
    60, 2 * 60, 3 * 60, 4 * 60, 5 * 60, 6 * 60,
    
  );
  $duration = array(0 => t('Unlimited')) + drupal_map_assoc($duration, 'format_interval');
  //$active = array(0 => t('Closed'), 1 => t('Active'));

  $form['settings'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#title' => t('Poll settings'),
    '#weight' => -3,
    '#access' => $admin,
  );

//  $form['settings']['active'] = array(
//    '#type' => 'radios',
//    '#title' => t('Poll status'),
//    '#default_value' => isset($node->active) ? $node->active : 1,
//    '#options' => $active,
//    '#description' => t('When a mimi_poll is closed, visitors can no longer vote for it.'),
//    '#access' => $admin,
//  );
  $form['settings']['runtime'] = array(
    '#type' => 'select',
    '#title' => t('Poll duration'),
    '#default_value' => isset($node->runtime) ? $node->runtime : 0,
    '#options' => $duration,
    '#description' => t('After this period, the mimi_poll will be closed automatically.'),
  );

  return $form;
}

/**
 * Submit handler to add more choices to a mimi_poll form.
 *
 * This handler is run regardless of whether JS is enabled or not. It makes
 * changes to the form state. If the button was clicked with JS disabled, then
 * the page is reloaded with the complete rebuilt form. If the button was
 * clicked with JS enabled, then ajax_form_callback() calls mimi_poll_choice_js() to
 * return just the changed part of the form.
 */
function mimi_poll_more_choices_submit($form, &$form_state) {
  // If this is a Ajax POST, add 1, otherwise add 5 more choices to the form.
  if ($form_state['values']['mimi_poll_more']) {
    $n = $_GET['q'] == 'system/ajax' ? 1 : 5;
    $form_state['choice_count'] = count($form_state['values']['choice']) + $n;
  }
  // Renumber the choices. This invalidates the corresponding key/value
  // associations in $form_state['input'], so clear that out. This requires
  // mimi_poll_form() to rebuild the choices with the values in
  // $form_state['node']->choice, which it does.
  $form_state['node']->choice = array_values($form_state['values']['choice']);
  unset($form_state['input']['choice']);
  $form_state['rebuild'] = TRUE;
}

function _mimi_poll_choice_form($key, $chid = NULL, $value = '', $votes = 0, $weight = 0, $size = 10) {
  $form = array(
    '#tree' => TRUE,
    '#weight' => $weight,
  );

  // We'll manually set the #parents property of these fields so that
  // their values appear in the $form_state['values']['choice'] array.
  $form['chid'] = array(
    '#type' => 'value',
    '#value' => $chid,
    '#parents' => array('choice', $key, 'chid'),
  );

  $form['chtext'] = array(
    '#type' => 'textfield',
    '#title' => $value !== '' ? t('Choice label') : t('New choice label'),
    '#title_display' => 'invisible',
    '#default_value' => $value,
    '#parents' => array('choice', $key, 'chtext'),
  );

  $form['chvotes'] = array(
    '#type' => 'textfield',
    '#title' => $value !== '' ? t('Vote count for choice @label', array('@label' => $value)) : t('Vote count for new choice'),
    '#title_display' => 'invisible',
    '#default_value' => $votes,
    '#size' => 5,
    '#maxlength' => 7,
    '#parents' => array('choice', $key, 'chvotes'),
    '#access' => user_access('administer nodes'),
    '#element_validate' => array('element_validate_integer'),
  );

  $form['weight'] = array(
    '#type' => 'weight',
    '#title' => $value !== '' ? t('Weight for choice @label', array('@label' => $value)) : t('Weight for new choice'),
    '#title_display' => 'invisible',
    '#default_value' => $weight,
    '#delta' => $size,
    '#parents' => array('choice', $key, 'weight'),
  );

  return $form;
}

/**
 * Ajax callback in response to new choices being added to the form.
 *
 * This returns the new page content to replace the page content made obsolete
 * by the form submission.
 *
 * @see mimi_poll_more_choices_submit()
 */
function mimi_poll_choice_js($form, $form_state) {
  return $form['choice_wrapper']['choice'];
}

/**
 * Form submit handler for node_form().
 *
 * Upon preview and final submission, we need to renumber mimi_poll choices and
 * create a teaser output.
 */
function mimi_poll_node_form_submit(&$form, &$form_state) {
  // Renumber choices.
  $form_state['values']['choice'] = array_values($form_state['values']['choice']);
  $form_state['values']['teaser'] = mimi_poll_teaser((object) $form_state['values']);
}

/**
 * Implements hook_validate().
 */
function mimi_poll_validate($node, $form) {
    // ## mimi_poll -- the title field is hidden @ CSS
    $node->title = "NA";
    // Check for at least two options and validate amount of votes.
    $realchoices = 0;
    foreach ($node->choice as $i => $choice) {
      if ($choice['chtext'] != '') {
        $realchoices++;
      }
      if (isset($choice['chvotes']) && $choice['chvotes'] < 0) {
        form_set_error("choice][$i][chvotes", t('Negative values are not allowed.'));
      }
    }

    if ($realchoices < 2) {
      form_set_error("choice][$realchoices][chtext", t('You must fill in at least two choices.'));
    }
}

/**
 * Implements hook_field_attach_prepare_translation_alter().
 */
function mimi_poll_field_attach_prepare_translation_alter(&$entity, $context) {
  if ($context['entity_type'] == 'node' && $entity->type == 'mimi_poll') {
    $entity->choice = $context['source_entity']->choice;
    foreach ($entity->choice as $i => $options) {
      $entity->choice[$i]['chvotes'] = 0;
    }
  }
}

/**
 * Implements hook_load().
 */
function mimi_poll_load($nodes) {
  global $user;
  foreach ($nodes as $node) {
    $mimi_poll = db_query("SELECT runtime  FROM {mimi_poll} WHERE nid = :nid", array(':nid' => $node->nid))->fetchObject();

    if (empty($mimi_poll)) {
      $mimi_poll = new stdClass();
    }

    // Load the appropriate choices into the $mimi_poll object.
    $mimi_poll->choice = db_select('mimi_poll_choice', 'c')
      ->addTag('translatable')
      ->fields('c', array('chid', 'chtext', 'chvotes', 'weight'))
      ->condition('c.nid', $node->nid)
      ->orderBy('weight')
      ->execute()->fetchAllAssoc('chid', PDO::FETCH_ASSOC);

    // Determine whether or not this user is allowed to vote.
//    $mimi_poll->allowvotes = FALSE;
//    if (user_access('vote on mimi_polls') && $mimi_poll->active) {
//      if ($user->uid) {
//        // If authenticated, find existing vote based on uid.
//        $mimi_poll->vote = db_query('SELECT chid FROM {mimi_poll_vote} WHERE nid = :nid AND uid = :uid', array(':nid' => $node->nid, ':uid' => $user->uid))->fetchField();
//        if (empty($mimi_poll->vote)) {
//          $mimi_poll->vote = -1;
//          $mimi_poll->allowvotes = TRUE;
//        }
//      }
////      elseif (!empty($_SESSION['mimi_poll_vote'][$node->nid])) {
////        // Otherwise the user is anonymous. Look for an existing vote in the
////        // user's session.
////        $mimi_poll->vote = $_SESSION['mimi_poll_vote'][$node->nid];
////      }
//      else {
//        // Finally, query the database for an existing vote based on anonymous
//        // user's hostname.
//        $mimi_poll->allowvotes = !db_query("SELECT 1 FROM {mimi_poll_vote} WHERE nid = :nid AND hostname = :hostname AND uid = 0", array(':nid' => $node->nid, ':hostname' => ip_address()))->fetchField();
//      }
//    }

//    avishay -- alwyas allow clients to vote
//                will handle voting perm at the clients side
    $mimi_poll->allowvotes = TRUE;
    foreach ($mimi_poll as $key => $value) {
      $nodes[$node->nid]->$key = $value;
    }
  }
}

/**
 * Implements hook_insert().
 */
function mimi_poll_insert($node) {
  if (!user_access('administer nodes')) {
    // Make sure all votes are 0 initially
    foreach ($node->choice as $i => $choice) {
      $node->choice[$i]['chvotes'] = 0;
    }
//    $node->active = 1;
  }

  db_insert('mimi_poll')
    ->fields(array(
      'nid' => $node->nid,
      'runtime' => $node->runtime,
//      'active' => $node->active,
    ))
    ->execute();

  foreach ($node->choice as $choice) {
    if ($choice['chtext'] != '') {
      db_insert('mimi_poll_choice')
        ->fields(array(
          'nid' => $node->nid,
          'chtext' => $choice['chtext'],
          'chvotes' => $choice['chvotes'],
          'weight' => $choice['weight'],
        ))
        ->execute();
    }
  }
}

/**
 * Implements hook_update().
 */
function mimi_poll_update($node) {
  // Update mimi_poll settings.
  db_update('mimi_poll')
    ->fields(array(
      'runtime' => $node->runtime,
//      'active' => $node->active,
    ))
    ->condition('nid', $node->nid)
    ->execute();

  
  // mimi_poll ---  NO need to reVote ...
  // Poll choices with empty titles signifies removal. We remove all votes to
  // the removed options, so people who voted on them can vote again.
//  foreach ($node->choice as $key => $choice) {
//    if (!empty($choice['chtext'])) {
//      db_merge('mimi_poll_choice')
//        ->key(array('chid' => $choice['chid']))
//        ->fields(array(
//          'chtext' => $choice['chtext'],
//          'chvotes' => (int) $choice['chvotes'],
//          'weight' => $choice['weight'],
//        ))
//        ->insertFields(array(
//          'nid' => $node->nid,
//          'chtext' => $choice['chtext'],
//          'chvotes' => (int) $choice['chvotes'],
//          'weight' => $choice['weight'],
//        ))
//        ->execute();
//    }
//    else {
//      db_delete('mimi_poll_vote')
//        ->condition('nid', $node->nid)
//        ->condition('chid', $key)
//        ->execute();
//      db_delete('mimi_poll_choice')
//        ->condition('nid', $node->nid)
//        ->condition('chid', $choice['chid'])
//        ->execute();
//    }
//  }
}

/**
 * Implements hook_delete().
 */
function mimi_poll_delete($node) {
  db_delete('mimi_poll')
    ->condition('nid', $node->nid)
    ->execute();
  db_delete('mimi_poll_choice')
    ->condition('nid', $node->nid)
    ->execute();
  db_delete('mimi_poll_vote')
    ->condition('nid', $node->nid)
    ->execute();
}

/**
 * Return content for 'latest mimi_poll' block.
 *
 * @param $node
 *   The node object to load.
 */
function mimi_poll_block_latest_mimi_poll_view($node) {
  global $user;
  $output = '';

  // This is necessary for shared objects because PHP doesn't copy objects, but
  // passes them by reference.  So when the objects are cached it can result in
  // the wrong output being displayed on subsequent calls.  The cloning and
  // unsetting of $node->content prevents the block output from being the same
  // as the node output.
  $node = clone $node;
  unset($node->content);

  // No 'read more' link.
  $node->readmore = FALSE;
  $node->teaser = '';

//  $links = array();
//  $links[] = array('title' => t('Older mimi_polls'), 'href' => 'mimi_poll', 'attributes' => array('title' => t('View the list of mimi_polls on this site.')));
//  if ($node->allowvotes) {
//    $links[] = array('title' => t('Results'), 'href' => 'node/' . $node->nid . '/results', 'attributes' => array('title' => t('View the current mimi_poll results.')));
//  }

  $node->links = FALSE;

  //if (!empty($node->allowvotes)) {
    $node->content['mimi_poll_view_voting'] = drupal_get_form('mimi_poll_view_voting', $node, TRUE);
//    $node->content['links'] = array(
//      '#theme' => 'links',
//      '#links' => $node->links,
//      '#weight' => 5,
//    );
//  }
//  else {
  //  $node->content['mimi_poll_view_results'] = array('#markup' => mimi_poll_view_results($node, TRUE, TRUE));
//  }

  return $node;
}


/**
 * Implements hook_view().
 */
function mimi_poll_view($node, $view_mode) {
  global $user;
  $output = '';

  if (empty($node->show_results)) {
    $node->content['mimi_poll_view_voting'] = drupal_get_form('mimi_poll_view_voting', $node);
  } 
  else {
    $node->content['mimi_poll_view_results'] = array('#markup' => mimi_poll_view_results($node, $view_mode));
  }
  return $node;
}

/**
 * Creates a simple teaser that lists all the choices.
 *
 * This is primarily used for RSS.
 */
function mimi_poll_teaser($node) {
  $teaser = NULL;
  if (is_array($node->choice)) {
    foreach ($node->choice as $k => $choice) {
      if ($choice['chtext'] != '') {
        $teaser .= '* ' . check_plain($choice['chtext']) . "\n";
      }
    }
  }
  return $teaser;
}

/**
 * Generates the voting form for a mimi_poll.
 *
 * @ingroup forms
 * @see mimi_poll_vote()
 * @see phptemplate_preprocess_mimi_poll_vote()
 */
function mimi_poll_view_voting($form, &$form_state, $node, $block = FALSE) {
  if ($node->choice) {
    $list = array();
    foreach ($node->choice as $i => $choice) {
      $list[$i] = check_plain($choice['chtext']);
    }
    $form['choice'] = array(
      '#type' => 'radios',
      '#title' => t('Choices'),
      '#title_display' => 'invisible',
      '#default_value' => -1,
      '#options' => $list,
    );
  }

  $form['vote'] = array(
    '#type' => 'submit',
    '#value' => t('Vote'),
    '#submit' => array('mimi_poll_vote'),
  );

  // Store the node so we can get to it in submit functions.
  $form['#node'] = $node;
  $form['#block'] = $block;

  // Set form caching because we could have multiple of these forms on
  // the same page, and we want to ensure the right one gets picked.
  $form_state['cache'] = TRUE;

  // Provide a more cleanly named voting form theme.
  $form['#theme'] = 'mimi_poll_vote';
  return $form;
}

/**
 * Validation function for processing votes
 */
function mimi_poll_view_voting_validate($form, &$form_state) {
  if ($form_state['values']['choice'] == -1) {
    form_set_error( 'choice', t('Your vote could not be recorded because you did not select any of the choices.'));
  }
}

/**
 * Submit handler for processing a vote.
 */
function mimi_poll_vote($form, &$form_state) {
  $node = $form['#node'];
  $choice = $form_state['values']['choice'];

  global $user;
  db_insert('mimi_poll_vote')
    ->fields(array(
      'nid' => $node->nid,
      'chid' => $choice,

      'uid' => $user->uid,
      'hostname' => ip_address().REQUEST_TIME,
      'timestamp' => REQUEST_TIME,
    ))
    ->execute();

  // Add one to the votes.
  db_update('mimi_poll_choice')
    ->expression('chvotes', 'chvotes + 1')
    ->condition('chid', $choice)
    ->execute();

  cache_clear_all();

  if (!$user->uid) {
    // The vote is recorded so the user gets the result view instead of the
    // voting form when viewing the mimi_poll. Saving a value in $_SESSION has the
    // convenient side effect of preventing the user from hitting the page
    // cache. When anonymous voting is allowed, the page cache should only
    // contain the voting form, not the results.
//    $_SESSION['mimi_poll_vote'][$node->nid] = $choice;
  }

  drupal_set_message(t('Your vote was recorded.'));

  // Return the user to whatever page they voted from.
}

/**
 * Themes the voting form for a mimi_poll.
 *
 * Inputs: $form
 */
function template_preprocess_mimi_poll_vote(&$variables) {
  $form = $variables['form'];
  $variables['choice'] = drupal_render($form['choice']);
  $variables['title'] = check_plain($form['#node']->title);
  $variables['vote'] = drupal_render($form['vote']);
  $variables['rest'] = drupal_render_children($form);
  $variables['block'] = $form['#block'];
  if ($variables['block']) {
    $variables['theme_hook_suggestions'][] = 'mimi_poll_vote__block';
  }
}

/**
 * Generates a graphical representation of the results of a mimi_poll.
 */
function mimi_poll_view_results($node, $view_mode, $block = FALSE) {
  // Make sure that choices are ordered by their weight.
  uasort($node->choice, 'drupal_sort_weight');

  // Count the votes and find the maximum.
  $total_votes = 0;
  $max_votes = 0;
  foreach ($node->choice as $choice) {
    if (isset($choice['chvotes'])) {
      $total_votes += $choice['chvotes'];
      $max_votes = max($max_votes, $choice['chvotes']);
    }
  }

  $mimi_poll_results = '';
  foreach ($node->choice as $i => $choice) {
    if (!empty($choice['chtext'])) {
      $chvotes = isset($choice['chvotes']) ? $choice['chvotes'] : NULL;
      $mimi_poll_results .= theme('mimi_poll_bar', array('title' => $choice['chtext'], 'votes' => $chvotes, 'total_votes' => $total_votes, 'vote' => isset($node->vote) && $node->vote == $i, 'block' => $block));
    }
  }

  return theme('mimi_poll_results', array('raw_title' => $node->title, 'results' => $mimi_poll_results, 'votes' => $total_votes, 'raw_links' => isset($node->links) ? $node->links : array(), 'block' => $block, 'nid' => $node->nid, 'vote' => isset($node->vote) ? $node->vote : NULL));
}


/**
 * Returns HTML for an admin mimi_poll form for choices.
 *
 * @param $variables
 *   An associative array containing:
 *   - form: A render element representing the form.
 *
 * @ingroup themeable
 */
function theme_mimi_poll_choices($variables) {
  $form = $variables['form'];

  drupal_add_tabledrag('mimi_poll-choice-table', 'order', 'sibling', 'mimi_poll-weight');

  $is_admin= user_access('administer nodes');
  $delta = 0;
  $rows = array();
  $headers = array('', t('Choice'));
  if ($is_admin) {
    $headers[] = t('Vote count');
  }
  $headers[] = t('Weight');

  foreach (element_children($form) as $key) {
    $delta++;
    // Set special classes for drag and drop updating.
    $form[$key]['weight']['#attributes']['class'] = array('mimi_poll-weight');

    // Build the table row.
    $row = array(
      'data' => array(
        array('class' => array('choice-flag')),
        drupal_render($form[$key]['chtext']),
      ),
      'class' => array('draggable'),
    );
    if ($is_admin) {
      $row['data'][] = drupal_render($form[$key]['chvotes']);
    }
    $row['data'][] = drupal_render($form[$key]['weight']);

    // Add any additional classes set on the row.
    if (!empty($form[$key]['#attributes']['class'])) {
      $row['class'] = array_merge($row['class'], $form[$key]['#attributes']['class']);
    }

    $rows[] = $row;
  }

  $output = theme('table', array('header' => $headers, 'rows' => $rows, 'attributes' => array('id' => 'mimi_poll-choice-table')));
  $output .= drupal_render_children($form);
  return $output;
}

/**
 * Preprocess the mimi_poll_results theme hook.
 *
 * Inputs: $raw_title, $results, $votes, $raw_links, $block, $nid, $vote. The
 * $raw_* inputs to this are naturally unsafe; often safe versions are
 * made to simply overwrite the raw version, but in this case it seems likely
 * that the title and the links may be overridden by the theme layer, so they
 * are left in with a different name for that purpose.
 *
 * @see mimi_poll-results.tpl.php
 * @see mimi_poll-results--block.tpl.php
 */
function template_preprocess_mimi_poll_results(&$variables) {
  $variables['links'] = theme('links__mimi_poll_results', array('links' => $variables['raw_links']));
  if (isset($variables['vote']) && $variables['vote'] > -1 && user_access('cancel own vote')) {
    $elements = drupal_get_form('mimi_poll_cancel_form', $variables['nid']);
    $variables['cancel_form'] = drupal_render($elements);
  }
  $variables['title'] = check_plain($variables['raw_title']);

  if ($variables['block']) {
    $variables['theme_hook_suggestions'][] = 'mimi_poll_results__block';
  }
}

/**
 * Preprocess the mimi_poll_bar theme hook.
 *
 * Inputs: $title, $votes, $total_votes, $voted, $block
 *
 * @see mimi_poll-bar.tpl.php
 * @see mimi_poll-bar--block.tpl.php
 * @see theme_mimi_poll_bar()
 */
function template_preprocess_mimi_poll_bar(&$variables) {
  if ($variables['block']) {
    $variables['theme_hook_suggestions'][] = 'mimi_poll_bar__block';
  }
  $variables['title'] = check_plain($variables['title']);
  $variables['percentage'] = round($variables['votes'] * 100 / max($variables['total_votes'], 1));
}

/**
 * Builds the cancel form for a mimi_poll.
 *
 * @ingroup forms
 * @see mimi_poll_cancel()
 */
function mimi_poll_cancel_form($form, &$form_state, $nid) {
  $form_state['cache'] = TRUE;

  // Store the nid so we can get to it in submit functions.
  $form['#nid'] = $nid;

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Cancel your vote'),
    '#submit' => array('mimi_poll_cancel')
  );

  return $form;
}

/**
 * Submit callback for mimi_poll_cancel_form().
 */
function mimi_poll_cancel($form, &$form_state) {
  global $user;
  $node = node_load($form['#nid']);

  db_delete('mimi_poll_vote')
    ->condition('nid', $node->nid)
    ->condition($user->uid ? 'uid' : 'hostname', $user->uid ? $user->uid : ip_address())
    ->execute();

  // Subtract from the votes.
  db_update('mimi_poll_choice')
    ->expression('chvotes', 'chvotes - 1')
    ->condition('chid', $node->vote)
    ->execute();

  unset($_SESSION['mimi_poll_vote'][$node->nid]);

  drupal_set_message(t('Your vote was cancelled.'));
}

/**
 * Implements hook_user_cancel().
 */
function mimi_poll_user_cancel($edit, $account, $method) {
  switch ($method) {
    case 'user_cancel_reassign':
      db_update('mimi_poll_vote')
        ->fields(array('uid' => 0))
        ->condition('uid', $account->uid)
        ->execute();
      break;
  }
}

/**
 * Implements hook_user_delete().
 */
function mimi_poll_user_delete($account) {
  db_delete('mimi_poll_vote')
    ->condition('uid', $account->uid)
    ->execute();
}

/**
 * Implements hook_rdf_mapping().
 */
function mimi_poll_rdf_mapping() {
  return array(
    array(
      'type' => 'node',
      'bundle' => 'mimi_poll',
      'mapping' => array(
        'rdftype' => array('sioc:Post', 'sioct:Poll'),
      ),
    ),
  );
}
